export const datas = [
  {
    id: 1,
    classCode: "zxczxc",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ha Noi",
    fsu: "FHN",
    classTime: "noon",
    status:"closed"
  },
  {
    id: 2,
    classCode: "Lorem",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Intern",
    location: "Ho Chi Minh",
    fsu: "FHM",
    classTime: "noon",
    status:"planning"
  },
  {
    id: 3,
    classCode: "HCM22_FR_DevOps_02",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Offline fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
    traine: "FDat",
    classTime: "morning",
    status:"planning"
  },
  {
    id: 4,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Offline fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
    classTime: "morning",
    status:"planning"
  },
  {
    id: 5,
    classCode: "HCM22_FR_DevOps_06",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 6,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 7,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 8,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 9,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 10,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 11,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 12,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 13,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 14,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
  {
    id: 15,
    classCode: "HCM22_FR_DevOps_01",
    trainingProgram: "DevOps Foundation",
    currentModule: "Linux",
    duration: "36 days",
    attendee: "Online fee-fresher",
    location: "Ho Chi Minh",
    fsu: "FHM",
  },
];
